import type { DropdownSeedOption } from './dropdown-data';

export type UpazilaSeedOption = DropdownSeedOption & {
  parentValue: string;
};

/** 495 upazilas — parentValue is district slug from district-data.ts */
export const UPAZILA_SEED: UpazilaSeedOption[] = [
  { value: 'bagerhat_sadar', label: 'Bagerhat Sadar', labelBn: 'বাগেরহাট সদর', parentValue: 'bagerhat' },
  { value: 'chitalmari', label: 'Chitalmari', labelBn: 'চিতলমারী', parentValue: 'bagerhat' },
  { value: 'fakirhat', label: 'Fakirhat', labelBn: 'ফকিরহাট', parentValue: 'bagerhat' },
  { value: 'kachua', label: 'Kachua', labelBn: 'কচুয়া', parentValue: 'bagerhat' },
  { value: 'mollahat', label: 'Mollahat', labelBn: 'মোল্লাহাট', parentValue: 'bagerhat' },
  { value: 'mongla', label: 'Mongla', labelBn: 'মোংলা', parentValue: 'bagerhat' },
  { value: 'morrelganj', label: 'Morrelganj', labelBn: 'মোড়েলগঞ্জ', parentValue: 'bagerhat' },
  { value: 'rampal', label: 'Rampal', labelBn: 'রামপাল', parentValue: 'bagerhat' },
  { value: 'sarankhola', label: 'Sarankhola', labelBn: 'শরণখোলা', parentValue: 'bagerhat' },
  { value: 'alikadam', label: 'Alikadam', labelBn: 'আলীকদম', parentValue: 'bandarban' },
  { value: 'bandarban_sadar', label: 'Bandarban Sadar', labelBn: 'বান্দরবান সদর', parentValue: 'bandarban' },
  { value: 'lama', label: 'Lama', labelBn: 'লামা', parentValue: 'bandarban' },
  { value: 'naikhongchhari', label: 'Naikhongchhari', labelBn: 'নাইক্ষ্যংছড়ি', parentValue: 'bandarban' },
  { value: 'rowangchhari', label: 'Rowangchhari', labelBn: 'রোয়াংছড়ি', parentValue: 'bandarban' },
  { value: 'ruma', label: 'Ruma', labelBn: 'রুমা', parentValue: 'bandarban' },
  { value: 'thanchi', label: 'Thanchi', labelBn: 'থানচি', parentValue: 'bandarban' },
  { value: 'amtali', label: 'Amtali', labelBn: 'আমতলী', parentValue: 'barguna' },
  { value: 'bamna', label: 'Bamna', labelBn: 'বামনা', parentValue: 'barguna' },
  { value: 'barguna_sadar', label: 'Barguna Sadar', labelBn: 'বরগুনা সদর', parentValue: 'barguna' },
  { value: 'betagi', label: 'Betagi', labelBn: 'বেতাগী', parentValue: 'barguna' },
  { value: 'pathorghata', label: 'Pathorghata', labelBn: 'পাথরঘাটা', parentValue: 'barguna' },
  { value: 'taltali', label: 'Taltali', labelBn: 'তালতলি', parentValue: 'barguna' },
  { value: 'agailjhara', label: 'Agailjhara', labelBn: 'আগৈলঝাড়া', parentValue: 'barishal' },
  { value: 'babuganj', label: 'Babuganj', labelBn: 'বাবুগঞ্জ', parentValue: 'barishal' },
  { value: 'bakerganj', label: 'Bakerganj', labelBn: 'বাকেরগঞ্জ', parentValue: 'barishal' },
  { value: 'banaripara', label: 'Banaripara', labelBn: 'বানারীপাড়া', parentValue: 'barishal' },
  { value: 'barisal_sadar', label: 'Barisal Sadar', labelBn: 'বরিশাল সদর', parentValue: 'barishal' },
  { value: 'gournadi', label: 'Gournadi', labelBn: 'গৌরনদী', parentValue: 'barishal' },
  { value: 'hizla', label: 'Hizla', labelBn: 'হিজলা', parentValue: 'barishal' },
  { value: 'mehendiganj', label: 'Mehendiganj', labelBn: 'মেহেন্দিগঞ্জ', parentValue: 'barishal' },
  { value: 'muladi', label: 'Muladi', labelBn: 'মুলাদী', parentValue: 'barishal' },
  { value: 'wazirpur', label: 'Wazirpur', labelBn: 'উজিরপুর', parentValue: 'barishal' },
  { value: 'bhola_sadar', label: 'Bhola Sadar', labelBn: 'ভোলা সদর', parentValue: 'bhola' },
  { value: 'borhanuddin', label: 'Borhanuddin', labelBn: 'বোরহানউদ্দিন', parentValue: 'bhola' },
  { value: 'charfesson', label: 'Charfesson', labelBn: 'চরফ্যাশন', parentValue: 'bhola' },
  { value: 'doulatkhan', label: 'Doulatkhan', labelBn: 'দৌলতখান', parentValue: 'bhola' },
  { value: 'lalmohan', label: 'Lalmohan', labelBn: 'লালমোহন', parentValue: 'bhola' },
  { value: 'monpura', label: 'Monpura', labelBn: 'মনপুরা', parentValue: 'bhola' },
  { value: 'tazumuddin', label: 'Tazumuddin', labelBn: 'তজুমদ্দিন', parentValue: 'bhola' },
  { value: 'adamdighi', label: 'Adamdighi', labelBn: 'আদমদিঘি', parentValue: 'bogura' },
  { value: 'bogra_sadar', label: 'Bogra Sadar', labelBn: 'বগুড়া সদর', parentValue: 'bogura' },
  { value: 'dhunot', label: 'Dhunot', labelBn: 'ধুনট', parentValue: 'bogura' },
  { value: 'dupchanchia', label: 'Dupchanchia', labelBn: 'দুপচাচিঁয়া', parentValue: 'bogura' },
  { value: 'gabtali', label: 'Gabtali', labelBn: 'গাবতলী', parentValue: 'bogura' },
  { value: 'kahaloo', label: 'Kahaloo', labelBn: 'কাহালু', parentValue: 'bogura' },
  { value: 'nondigram', label: 'Nondigram', labelBn: 'নন্দিগ্রাম', parentValue: 'bogura' },
  { value: 'shajahanpur', label: 'Shajahanpur', labelBn: 'শাজাহানপুর', parentValue: 'bogura' },
  { value: 'shariakandi', label: 'Shariakandi', labelBn: 'সারিয়াকান্দি', parentValue: 'bogura' },
  { value: 'sherpur', label: 'Sherpur', labelBn: 'শেরপুর', parentValue: 'bogura' },
  { value: 'shibganj', label: 'Shibganj', labelBn: 'শিবগঞ্জ', parentValue: 'bogura' },
  { value: 'sonatala', label: 'Sonatala', labelBn: 'সোনাতলা', parentValue: 'bogura' },
  { value: 'akhaura', label: 'Akhaura', labelBn: 'আখাউড়া', parentValue: 'brahmanbaria' },
  { value: 'ashuganj', label: 'Ashuganj', labelBn: 'আশুগঞ্জ', parentValue: 'brahmanbaria' },
  { value: 'bancharampur', label: 'Bancharampur', labelBn: 'বাঞ্ছারামপুর', parentValue: 'brahmanbaria' },
  { value: 'bijoynagar', label: 'Bijoynagar', labelBn: 'বিজয়নগর', parentValue: 'brahmanbaria' },
  { value: 'brahmanbaria_sadar', label: 'Brahmanbaria Sadar', labelBn: 'ব্রাহ্মণবাড়িয়া সদর', parentValue: 'brahmanbaria' },
  { value: 'kasba', label: 'Kasba', labelBn: 'কসবা', parentValue: 'brahmanbaria' },
  { value: 'nabinagar', label: 'Nabinagar', labelBn: 'নবীনগর', parentValue: 'brahmanbaria' },
  { value: 'nasirnagar', label: 'Nasirnagar', labelBn: 'নাসিরনগর', parentValue: 'brahmanbaria' },
  { value: 'sarail', label: 'Sarail', labelBn: 'সরাইল', parentValue: 'brahmanbaria' },
  { value: 'chandpur_sadar', label: 'Chandpur Sadar', labelBn: 'চাঁদপুর সদর', parentValue: 'chandpur' },
  { value: 'faridgonj', label: 'Faridgonj', labelBn: 'ফরিদগঞ্জ', parentValue: 'chandpur' },
  { value: 'haimchar', label: 'Haimchar', labelBn: 'হাইমচর', parentValue: 'chandpur' },
  { value: 'hajiganj', label: 'Hajiganj', labelBn: 'হাজীগঞ্জ', parentValue: 'chandpur' },
  { value: 'kachua', label: 'Kachua', labelBn: 'কচুয়া', parentValue: 'chandpur' },
  { value: 'matlab_north', label: 'Matlab North', labelBn: 'মতলব উত্তর', parentValue: 'chandpur' },
  { value: 'matlab_south', label: 'Matlab South', labelBn: 'মতলব দক্ষিণ', parentValue: 'chandpur' },
  { value: 'shahrasti', label: 'Shahrasti', labelBn: 'শাহরাস্তি	', parentValue: 'chandpur' },
  { value: 'bholahat', label: 'Bholahat', labelBn: 'ভোলাহাট', parentValue: 'chapainawabganj' },
  { value: 'chapainawabganj_sadar', label: 'Chapainawabganj Sadar', labelBn: 'চাঁপাইনবাবগঞ্জ সদর', parentValue: 'chapainawabganj' },
  { value: 'gomostapur', label: 'Gomostapur', labelBn: 'গোমস্তাপুর', parentValue: 'chapainawabganj' },
  { value: 'nachol', label: 'Nachol', labelBn: 'নাচোল', parentValue: 'chapainawabganj' },
  { value: 'shibganj', label: 'Shibganj', labelBn: 'শিবগঞ্জ', parentValue: 'chapainawabganj' },
  { value: 'anwara', label: 'Anwara', labelBn: 'আনোয়ারা', parentValue: 'chattogram' },
  { value: 'banshkhali', label: 'Banshkhali', labelBn: 'বাঁশখালী', parentValue: 'chattogram' },
  { value: 'boalkhali', label: 'Boalkhali', labelBn: 'বোয়ালখালী', parentValue: 'chattogram' },
  { value: 'chandanaish', label: 'Chandanaish', labelBn: 'চন্দনাইশ', parentValue: 'chattogram' },
  { value: 'fatikchhari', label: 'Fatikchhari', labelBn: 'ফটিকছড়ি', parentValue: 'chattogram' },
  { value: 'hathazari', label: 'Hathazari', labelBn: 'হাটহাজারী', parentValue: 'chattogram' },
  { value: 'karnafuli', label: 'Karnafuli', labelBn: 'কর্ণফুলী', parentValue: 'chattogram' },
  { value: 'lohagara', label: 'Lohagara', labelBn: 'লোহাগাড়া', parentValue: 'chattogram' },
  { value: 'mirsharai', label: 'Mirsharai', labelBn: 'মীরসরাই', parentValue: 'chattogram' },
  { value: 'patiya', label: 'Patiya', labelBn: 'পটিয়া', parentValue: 'chattogram' },
  { value: 'rangunia', label: 'Rangunia', labelBn: 'রাঙ্গুনিয়া', parentValue: 'chattogram' },
  { value: 'raozan', label: 'Raozan', labelBn: 'রাউজান', parentValue: 'chattogram' },
  { value: 'sandwip', label: 'Sandwip', labelBn: 'সন্দ্বীপ', parentValue: 'chattogram' },
  { value: 'satkania', label: 'Satkania', labelBn: 'সাতকানিয়া', parentValue: 'chattogram' },
  { value: 'sitakunda', label: 'Sitakunda', labelBn: 'সীতাকুন্ড', parentValue: 'chattogram' },
  { value: 'alamdanga', label: 'Alamdanga', labelBn: 'আলমডাঙ্গা', parentValue: 'chuadanga' },
  { value: 'chuadanga_sadar', label: 'Chuadanga Sadar', labelBn: 'চুয়াডাঙ্গা সদর', parentValue: 'chuadanga' },
  { value: 'damurhuda', label: 'Damurhuda', labelBn: 'দামুড়হুদা', parentValue: 'chuadanga' },
  { value: 'jibannagar', label: 'Jibannagar', labelBn: 'জীবননগর', parentValue: 'chuadanga' },
  { value: 'chakaria', label: 'Chakaria', labelBn: 'চকরিয়া', parentValue: 'coxs_bazar' },
  { value: 'coxsbazar_sadar', label: 'Coxsbazar Sadar', labelBn: 'কক্সবাজার সদর', parentValue: 'coxs_bazar' },
  { value: 'eidgaon', label: 'Eidgaon', labelBn: 'ঈদগাঁও', parentValue: 'coxs_bazar' },
  { value: 'kutubdia', label: 'Kutubdia', labelBn: 'কুতুবদিয়া', parentValue: 'coxs_bazar' },
  { value: 'moheshkhali', label: 'Moheshkhali', labelBn: 'মহেশখালী', parentValue: 'coxs_bazar' },
  { value: 'pekua', label: 'Pekua', labelBn: 'পেকুয়া', parentValue: 'coxs_bazar' },
  { value: 'ramu', label: 'Ramu', labelBn: 'রামু', parentValue: 'coxs_bazar' },
  { value: 'teknaf', label: 'Teknaf', labelBn: 'টেকনাফ', parentValue: 'coxs_bazar' },
  { value: 'ukhiya', label: 'Ukhiya', labelBn: 'উখিয়া', parentValue: 'coxs_bazar' },
  { value: 'barura', label: 'Barura', labelBn: 'বরুড়া', parentValue: 'cumilla' },
  { value: 'brahmanpara', label: 'Brahmanpara', labelBn: 'ব্রাহ্মণপাড়া', parentValue: 'cumilla' },
  { value: 'burichang', label: 'Burichang', labelBn: 'বুড়িচং', parentValue: 'cumilla' },
  { value: 'chandina', label: 'Chandina', labelBn: 'চান্দিনা', parentValue: 'cumilla' },
  { value: 'chauddagram', label: 'Chauddagram', labelBn: 'চৌদ্দগ্রাম', parentValue: 'cumilla' },
  { value: 'comilla_sadar', label: 'Comilla Sadar', labelBn: 'কুমিল্লা সদর', parentValue: 'cumilla' },
  { value: 'daudkandi', label: 'Daudkandi', labelBn: 'দাউদকান্দি', parentValue: 'cumilla' },
  { value: 'debidwar', label: 'Debidwar', labelBn: 'দেবিদ্বার', parentValue: 'cumilla' },
  { value: 'homna', label: 'Homna', labelBn: 'হোমনা', parentValue: 'cumilla' },
  { value: 'laksam', label: 'Laksam', labelBn: 'লাকসাম', parentValue: 'cumilla' },
  { value: 'lalmai', label: 'Lalmai', labelBn: 'লালমাই', parentValue: 'cumilla' },
  { value: 'meghna', label: 'Meghna', labelBn: 'মেঘনা', parentValue: 'cumilla' },
  { value: 'monohargonj', label: 'Monohargonj', labelBn: 'মনোহরগঞ্জ', parentValue: 'cumilla' },
  { value: 'muradnagar', label: 'Muradnagar', labelBn: 'মুরাদনগর', parentValue: 'cumilla' },
  { value: 'nangalkot', label: 'Nangalkot', labelBn: 'নাঙ্গলকোট', parentValue: 'cumilla' },
  { value: 'sadarsouth', label: 'Sadarsouth', labelBn: 'সদর দক্ষিণ', parentValue: 'cumilla' },
  { value: 'titas', label: 'Titas', labelBn: 'তিতাস', parentValue: 'cumilla' },
  { value: 'dhamrai', label: 'Dhamrai', labelBn: 'ধামরাই', parentValue: 'dhaka' },
  { value: 'dohar', label: 'Dohar', labelBn: 'দোহার', parentValue: 'dhaka' },
  { value: 'keraniganj', label: 'Keraniganj', labelBn: 'কেরাণীগঞ্জ', parentValue: 'dhaka' },
  { value: 'nawabganj', label: 'Nawabganj', labelBn: 'নবাবগঞ্জ', parentValue: 'dhaka' },
  { value: 'savar', label: 'Savar', labelBn: 'সাভার', parentValue: 'dhaka' },
  { value: 'birampur', label: 'Birampur', labelBn: 'বিরামপুর', parentValue: 'dinajpur' },
  { value: 'birganj', label: 'Birganj', labelBn: 'বীরগঞ্জ', parentValue: 'dinajpur' },
  { value: 'birol', label: 'Birol', labelBn: 'বিরল', parentValue: 'dinajpur' },
  { value: 'bochaganj', label: 'Bochaganj', labelBn: 'বোচাগঞ্জ', parentValue: 'dinajpur' },
  { value: 'chirirbandar', label: 'Chirirbandar', labelBn: 'চিরিরবন্দর', parentValue: 'dinajpur' },
  { value: 'dinajpur_sadar', label: 'Dinajpur Sadar', labelBn: 'দিনাজপুর সদর', parentValue: 'dinajpur' },
  { value: 'fulbari', label: 'Fulbari', labelBn: 'ফুলবাড়ী', parentValue: 'dinajpur' },
  { value: 'ghoraghat', label: 'Ghoraghat', labelBn: 'ঘোড়াঘাট', parentValue: 'dinajpur' },
  { value: 'hakimpur', label: 'Hakimpur', labelBn: 'হাকিমপুর', parentValue: 'dinajpur' },
  { value: 'kaharol', label: 'Kaharol', labelBn: 'কাহারোল', parentValue: 'dinajpur' },
  { value: 'khansama', label: 'Khansama', labelBn: 'খানসামা', parentValue: 'dinajpur' },
  { value: 'nawabganj', label: 'Nawabganj', labelBn: 'নবাবগঞ্জ', parentValue: 'dinajpur' },
  { value: 'parbatipur', label: 'Parbatipur', labelBn: 'পার্বতীপুর', parentValue: 'dinajpur' },
  { value: 'alfadanga', label: 'Alfadanga', labelBn: 'আলফাডাঙ্গা', parentValue: 'faridpur' },
  { value: 'bhanga', label: 'Bhanga', labelBn: 'ভাঙ্গা', parentValue: 'faridpur' },
  { value: 'boalmari', label: 'Boalmari', labelBn: 'বোয়ালমারী', parentValue: 'faridpur' },
  { value: 'charbhadrasan', label: 'Charbhadrasan', labelBn: 'চরভদ্রাসন', parentValue: 'faridpur' },
  { value: 'faridpur_sadar', label: 'Faridpur Sadar', labelBn: 'ফরিদপুর সদর', parentValue: 'faridpur' },
  { value: 'madhukhali', label: 'Madhukhali', labelBn: 'মধুখালী', parentValue: 'faridpur' },
  { value: 'nagarkanda', label: 'Nagarkanda', labelBn: 'নগরকান্দা', parentValue: 'faridpur' },
  { value: 'sadarpur', label: 'Sadarpur', labelBn: 'সদরপুর', parentValue: 'faridpur' },
  { value: 'saltha', label: 'Saltha', labelBn: 'সালথা', parentValue: 'faridpur' },
  { value: 'chhagalnaiya', label: 'Chhagalnaiya', labelBn: 'ছাগলনাইয়া', parentValue: 'feni' },
  { value: 'daganbhuiyan', label: 'Daganbhuiyan', labelBn: 'দাগনভূঞা', parentValue: 'feni' },
  { value: 'feni_sadar', label: 'Feni Sadar', labelBn: 'ফেনী সদর', parentValue: 'feni' },
  { value: 'fulgazi', label: 'Fulgazi', labelBn: 'ফুলগাজী', parentValue: 'feni' },
  { value: 'parshuram', label: 'Parshuram', labelBn: 'পরশুরাম', parentValue: 'feni' },
  { value: 'sonagazi', label: 'Sonagazi', labelBn: 'সোনাগাজী', parentValue: 'feni' },
  { value: 'gaibandha_sadar', label: 'Gaibandha Sadar', labelBn: 'গাইবান্ধা সদর', parentValue: 'gaibandha' },
  { value: 'gobindaganj', label: 'Gobindaganj', labelBn: 'গোবিন্দগঞ্জ', parentValue: 'gaibandha' },
  { value: 'palashbari', label: 'Palashbari', labelBn: 'পলাশবাড়ী', parentValue: 'gaibandha' },
  { value: 'phulchari', label: 'Phulchari', labelBn: 'ফুলছড়ি', parentValue: 'gaibandha' },
  { value: 'sadullapur', label: 'Sadullapur', labelBn: 'সাদুল্লাপুর', parentValue: 'gaibandha' },
  { value: 'saghata', label: 'Saghata', labelBn: 'সাঘাটা', parentValue: 'gaibandha' },
  { value: 'sundarganj', label: 'Sundarganj', labelBn: 'সুন্দরগঞ্জ', parentValue: 'gaibandha' },
  { value: 'gazipur_sadar', label: 'Gazipur Sadar', labelBn: 'গাজীপুর সদর', parentValue: 'gazipur' },
  { value: 'kaliakair', label: 'Kaliakair', labelBn: 'কালিয়াকৈর', parentValue: 'gazipur' },
  { value: 'kaliganj', label: 'Kaliganj', labelBn: 'কালীগঞ্জ', parentValue: 'gazipur' },
  { value: 'kapasia', label: 'Kapasia', labelBn: 'কাপাসিয়া', parentValue: 'gazipur' },
  { value: 'sreepur', label: 'Sreepur', labelBn: 'শ্রীপুর', parentValue: 'gazipur' },
  { value: 'gopalganj_sadar', label: 'Gopalganj Sadar', labelBn: 'গোপালগঞ্জ সদর', parentValue: 'gopalganj' },
  { value: 'kashiani', label: 'Kashiani', labelBn: 'কাশিয়ানী', parentValue: 'gopalganj' },
  { value: 'kotalipara', label: 'Kotalipara', labelBn: 'কোটালীপাড়া', parentValue: 'gopalganj' },
  { value: 'muksudpur', label: 'Muksudpur', labelBn: 'মুকসুদপুর', parentValue: 'gopalganj' },
  { value: 'tungipara', label: 'Tungipara', labelBn: 'টুংগীপাড়া', parentValue: 'gopalganj' },
  { value: 'ajmiriganj', label: 'Ajmiriganj', labelBn: 'আজমিরীগঞ্জ', parentValue: 'habiganj' },
  { value: 'bahubal', label: 'Bahubal', labelBn: 'বাহুবল', parentValue: 'habiganj' },
  { value: 'baniachong', label: 'Baniachong', labelBn: 'বানিয়াচং', parentValue: 'habiganj' },
  { value: 'chunarughat', label: 'Chunarughat', labelBn: 'চুনারুঘাট', parentValue: 'habiganj' },
  { value: 'habiganj_sadar', label: 'Habiganj Sadar', labelBn: 'হবিগঞ্জ সদর', parentValue: 'habiganj' },
  { value: 'lakhai', label: 'Lakhai', labelBn: 'লাখাই', parentValue: 'habiganj' },
  { value: 'madhabpur', label: 'Madhabpur', labelBn: 'মাধবপুর', parentValue: 'habiganj' },
  { value: 'nabiganj', label: 'Nabiganj', labelBn: 'নবীগঞ্জ', parentValue: 'habiganj' },
  { value: 'shaistaganj', label: 'Shaistaganj', labelBn: 'শায়েস্তাগঞ্জ', parentValue: 'habiganj' },
  { value: 'bokshiganj', label: 'Bokshiganj', labelBn: 'বকশীগঞ্জ', parentValue: 'jamalpur' },
  { value: 'dewangonj', label: 'Dewangonj', labelBn: 'দেওয়ানগঞ্জ', parentValue: 'jamalpur' },
  { value: 'islampur', label: 'Islampur', labelBn: 'ইসলামপুর', parentValue: 'jamalpur' },
  { value: 'jamalpur_sadar', label: 'Jamalpur Sadar', labelBn: 'জামালপুর সদর', parentValue: 'jamalpur' },
  { value: 'madarganj', label: 'Madarganj', labelBn: 'মাদারগঞ্জ', parentValue: 'jamalpur' },
  { value: 'melandah', label: 'Melandah', labelBn: 'মেলান্দহ', parentValue: 'jamalpur' },
  { value: 'sarishabari', label: 'Sarishabari', labelBn: 'সরিষাবাড়ী', parentValue: 'jamalpur' },
  { value: 'abhaynagar', label: 'Abhaynagar', labelBn: 'অভয়নগর', parentValue: 'jashore' },
  { value: 'bagherpara', label: 'Bagherpara', labelBn: 'বাঘারপাড়া', parentValue: 'jashore' },
  { value: 'chougachha', label: 'Chougachha', labelBn: 'চৌগাছা', parentValue: 'jashore' },
  { value: 'jessore_sadar', label: 'Jessore Sadar', labelBn: 'যশোর সদর', parentValue: 'jashore' },
  { value: 'jhikargacha', label: 'Jhikargacha', labelBn: 'ঝিকরগাছা', parentValue: 'jashore' },
  { value: 'keshabpur', label: 'Keshabpur', labelBn: 'কেশবপুর', parentValue: 'jashore' },
  { value: 'manirampur', label: 'Manirampur', labelBn: 'মণিরামপুর', parentValue: 'jashore' },
  { value: 'sharsha', label: 'Sharsha', labelBn: 'শার্শা', parentValue: 'jashore' },
  { value: 'jhalakathi_sadar', label: 'Jhalakathi Sadar', labelBn: 'ঝালকাঠি সদর', parentValue: 'jhalokati' },
  { value: 'kathalia', label: 'Kathalia', labelBn: 'কাঠালিয়া', parentValue: 'jhalokati' },
  { value: 'nalchity', label: 'Nalchity', labelBn: 'নলছিটি', parentValue: 'jhalokati' },
  { value: 'rajapur', label: 'Rajapur', labelBn: 'রাজাপুর', parentValue: 'jhalokati' },
  { value: 'harinakundu', label: 'Harinakundu', labelBn: 'হরিণাকুন্ডু', parentValue: 'jhenaidah' },
  { value: 'jhenaidah_sadar', label: 'Jhenaidah Sadar', labelBn: 'ঝিনাইদহ সদর', parentValue: 'jhenaidah' },
  { value: 'kaliganj', label: 'Kaliganj', labelBn: 'কালীগঞ্জ', parentValue: 'jhenaidah' },
  { value: 'kotchandpur', label: 'Kotchandpur', labelBn: 'কোটচাঁদপুর', parentValue: 'jhenaidah' },
  { value: 'moheshpur', label: 'Moheshpur', labelBn: 'মহেশপুর', parentValue: 'jhenaidah' },
  { value: 'shailkupa', label: 'Shailkupa', labelBn: 'শৈলকুপা', parentValue: 'jhenaidah' },
  { value: 'akkelpur', label: 'Akkelpur', labelBn: 'আক্কেলপুর', parentValue: 'joypurhat' },
  { value: 'joypurhat_sadar', label: 'Joypurhat Sadar', labelBn: 'জয়পুরহাট সদর', parentValue: 'joypurhat' },
  { value: 'kalai', label: 'Kalai', labelBn: 'কালাই', parentValue: 'joypurhat' },
  { value: 'khetlal', label: 'Khetlal', labelBn: 'ক্ষেতলাল', parentValue: 'joypurhat' },
  { value: 'panchbibi', label: 'Panchbibi', labelBn: 'পাঁচবিবি', parentValue: 'joypurhat' },
  { value: 'dighinala', label: 'Dighinala', labelBn: 'দিঘীনালা', parentValue: 'khagrachhari' },
  { value: 'guimara', label: 'Guimara', labelBn: 'গুইমারা', parentValue: 'khagrachhari' },
  { value: 'khagrachhari_sadar', label: 'Khagrachhari Sadar', labelBn: 'খাগড়াছড়ি সদর', parentValue: 'khagrachhari' },
  { value: 'laxmichhari', label: 'Laxmichhari', labelBn: 'লক্ষীছড়ি', parentValue: 'khagrachhari' },
  { value: 'manikchari', label: 'Manikchari', labelBn: 'মানিকছড়ি', parentValue: 'khagrachhari' },
  { value: 'matiranga', label: 'Matiranga', labelBn: 'মাটিরাঙ্গা', parentValue: 'khagrachhari' },
  { value: 'mohalchari', label: 'Mohalchari', labelBn: 'মহালছড়ি', parentValue: 'khagrachhari' },
  { value: 'panchari', label: 'Panchari', labelBn: 'পানছড়ি', parentValue: 'khagrachhari' },
  { value: 'ramgarh', label: 'Ramgarh', labelBn: 'রামগড়', parentValue: 'khagrachhari' },
  { value: 'botiaghata', label: 'Botiaghata', labelBn: 'বটিয়াঘাটা', parentValue: 'khulna' },
  { value: 'dakop', label: 'Dakop', labelBn: 'দাকোপ', parentValue: 'khulna' },
  { value: 'digholia', label: 'Digholia', labelBn: 'দিঘলিয়া', parentValue: 'khulna' },
  { value: 'dumuria', label: 'Dumuria', labelBn: 'ডুমুরিয়া', parentValue: 'khulna' },
  { value: 'fultola', label: 'Fultola', labelBn: 'ফুলতলা', parentValue: 'khulna' },
  { value: 'koyra', label: 'Koyra', labelBn: 'কয়রা', parentValue: 'khulna' },
  { value: 'paikgasa', label: 'Paikgasa', labelBn: 'পাইকগাছা', parentValue: 'khulna' },
  { value: 'rupsha', label: 'Rupsha', labelBn: 'রূপসা', parentValue: 'khulna' },
  { value: 'terokhada', label: 'Terokhada', labelBn: 'তেরখাদা', parentValue: 'khulna' },
  { value: 'austagram', label: 'Austagram', labelBn: 'অষ্টগ্রাম', parentValue: 'kishoreganj' },
  { value: 'bajitpur', label: 'Bajitpur', labelBn: 'বাজিতপুর', parentValue: 'kishoreganj' },
  { value: 'bhairab', label: 'Bhairab', labelBn: 'ভৈরব', parentValue: 'kishoreganj' },
  { value: 'hossainpur', label: 'Hossainpur', labelBn: 'হোসেনপুর', parentValue: 'kishoreganj' },
  { value: 'itna', label: 'Itna', labelBn: 'ইটনা', parentValue: 'kishoreganj' },
  { value: 'karimgonj', label: 'Karimgonj', labelBn: 'করিমগঞ্জ', parentValue: 'kishoreganj' },
  { value: 'katiadi', label: 'Katiadi', labelBn: 'কটিয়াদী', parentValue: 'kishoreganj' },
  { value: 'kishoreganj_sadar', label: 'Kishoreganj Sadar', labelBn: 'কিশোরগঞ্জ সদর', parentValue: 'kishoreganj' },
  { value: 'kuliarchar', label: 'Kuliarchar', labelBn: 'কুলিয়ারচর', parentValue: 'kishoreganj' },
  { value: 'mithamoin', label: 'Mithamoin', labelBn: 'মিঠামইন', parentValue: 'kishoreganj' },
  { value: 'nikli', label: 'Nikli', labelBn: 'নিকলী', parentValue: 'kishoreganj' },
  { value: 'pakundia', label: 'Pakundia', labelBn: 'পাকুন্দিয়া', parentValue: 'kishoreganj' },
  { value: 'tarail', label: 'Tarail', labelBn: 'তাড়াইল', parentValue: 'kishoreganj' },
  { value: 'bhurungamari', label: 'Bhurungamari', labelBn: 'ভুরুঙ্গামারী', parentValue: 'kurigram' },
  { value: 'charrajibpur', label: 'Charrajibpur', labelBn: 'চর রাজিবপুর', parentValue: 'kurigram' },
  { value: 'chilmari', label: 'Chilmari', labelBn: 'চিলমারী', parentValue: 'kurigram' },
  { value: 'kurigram_sadar', label: 'Kurigram Sadar', labelBn: 'কুড়িগ্রাম সদর', parentValue: 'kurigram' },
  { value: 'nageshwari', label: 'Nageshwari', labelBn: 'নাগেশ্বরী', parentValue: 'kurigram' },
  { value: 'phulbari', label: 'Phulbari', labelBn: 'ফুলবাড়ী', parentValue: 'kurigram' },
  { value: 'rajarhat', label: 'Rajarhat', labelBn: 'রাজারহাট', parentValue: 'kurigram' },
  { value: 'rowmari', label: 'Rowmari', labelBn: 'রৌমারী', parentValue: 'kurigram' },
  { value: 'ulipur', label: 'Ulipur', labelBn: 'উলিপুর', parentValue: 'kurigram' },
  { value: 'bheramara', label: 'Bheramara', labelBn: 'ভেড়ামারা', parentValue: 'kushtia' },
  { value: 'daulatpur', label: 'Daulatpur', labelBn: 'দৌলতপুর', parentValue: 'kushtia' },
  { value: 'khoksa', label: 'Khoksa', labelBn: 'খোকসা', parentValue: 'kushtia' },
  { value: 'kumarkhali', label: 'Kumarkhali', labelBn: 'কুমারখালী', parentValue: 'kushtia' },
  { value: 'kushtia_sadar', label: 'Kushtia Sadar', labelBn: 'কুষ্টিয়া সদর', parentValue: 'kushtia' },
  { value: 'mirpur', label: 'Mirpur', labelBn: 'মিরপুর', parentValue: 'kushtia' },
  { value: 'kamalnagar', label: 'Kamalnagar', labelBn: 'কমলনগর', parentValue: 'lakshmipur' },
  { value: 'lakshmipur_sadar', label: 'Lakshmipur Sadar', labelBn: 'লক্ষ্মীপুর সদর', parentValue: 'lakshmipur' },
  { value: 'raipur', label: 'Raipur', labelBn: 'রায়পুর', parentValue: 'lakshmipur' },
  { value: 'ramganj', label: 'Ramganj', labelBn: 'রামগঞ্জ', parentValue: 'lakshmipur' },
  { value: 'ramgati', label: 'Ramgati', labelBn: 'রামগতি', parentValue: 'lakshmipur' },
  { value: 'aditmari', label: 'Aditmari', labelBn: 'আদিতমারী', parentValue: 'lalmonirhat' },
  { value: 'hatibandha', label: 'Hatibandha', labelBn: 'হাতীবান্ধা', parentValue: 'lalmonirhat' },
  { value: 'kaliganj', label: 'Kaliganj', labelBn: 'কালীগঞ্জ', parentValue: 'lalmonirhat' },
  { value: 'lalmonirhat_sadar', label: 'Lalmonirhat Sadar', labelBn: 'লালমনিরহাট সদর', parentValue: 'lalmonirhat' },
  { value: 'patgram', label: 'Patgram', labelBn: 'পাটগ্রাম', parentValue: 'lalmonirhat' },
  { value: 'dasar', label: 'Dasar', labelBn: 'ডাসার', parentValue: 'madaripur' },
  { value: 'kalkini', label: 'Kalkini', labelBn: 'কালকিনি', parentValue: 'madaripur' },
  { value: 'madaripur_sadar', label: 'Madaripur Sadar', labelBn: 'মাদারীপুর সদর', parentValue: 'madaripur' },
  { value: 'rajoir', label: 'Rajoir', labelBn: 'রাজৈর', parentValue: 'madaripur' },
  { value: 'shibchar', label: 'Shibchar', labelBn: 'শিবচর', parentValue: 'madaripur' },
  { value: 'magura_sadar', label: 'Magura Sadar', labelBn: 'মাগুরা সদর', parentValue: 'magura' },
  { value: 'mohammadpur', label: 'Mohammadpur', labelBn: 'মহম্মদপুর', parentValue: 'magura' },
  { value: 'shalikha', label: 'Shalikha', labelBn: 'শালিখা', parentValue: 'magura' },
  { value: 'sreepur', label: 'Sreepur', labelBn: 'শ্রীপুর', parentValue: 'magura' },
  { value: 'doulatpur', label: 'Doulatpur', labelBn: 'দৌলতপুর', parentValue: 'manikganj' },
  { value: 'gior', label: 'Gior', labelBn: 'ঘিওর', parentValue: 'manikganj' },
  { value: 'harirampur', label: 'Harirampur', labelBn: 'হরিরামপুর', parentValue: 'manikganj' },
  { value: 'manikganj_sadar', label: 'Manikganj Sadar', labelBn: 'মানিকগঞ্জ সদর', parentValue: 'manikganj' },
  { value: 'saturia', label: 'Saturia', labelBn: 'সাটুরিয়া', parentValue: 'manikganj' },
  { value: 'shibaloy', label: 'Shibaloy', labelBn: 'শিবালয়', parentValue: 'manikganj' },
  { value: 'singiar', label: 'Singiar', labelBn: 'সিংগাইর', parentValue: 'manikganj' },
  { value: 'gangni', label: 'Gangni', labelBn: 'গাংনী', parentValue: 'meherpur' },
  { value: 'meherpur_sadar', label: 'Meherpur Sadar', labelBn: 'মেহেরপুর সদর', parentValue: 'meherpur' },
  { value: 'mujibnagar', label: 'Mujibnagar', labelBn: 'মুজিবনগর', parentValue: 'meherpur' },
  { value: 'barlekha', label: 'Barlekha', labelBn: 'বড়লেখা', parentValue: 'moulvibazar' },
  { value: 'juri', label: 'Juri', labelBn: 'জুড়ী', parentValue: 'moulvibazar' },
  { value: 'kamolganj', label: 'Kamolganj', labelBn: 'কমলগঞ্জ', parentValue: 'moulvibazar' },
  { value: 'kulaura', label: 'Kulaura', labelBn: 'কুলাউড়া', parentValue: 'moulvibazar' },
  { value: 'moulvibazar_sadar', label: 'Moulvibazar Sadar', labelBn: 'মৌলভীবাজার সদর', parentValue: 'moulvibazar' },
  { value: 'rajnagar', label: 'Rajnagar', labelBn: 'রাজনগর', parentValue: 'moulvibazar' },
  { value: 'sreemangal', label: 'Sreemangal', labelBn: 'শ্রীমঙ্গল', parentValue: 'moulvibazar' },
  { value: 'gajaria', label: 'Gajaria', labelBn: 'গজারিয়া', parentValue: 'munshiganj' },
  { value: 'louhajanj', label: 'Louhajanj', labelBn: 'লৌহজং', parentValue: 'munshiganj' },
  { value: 'munshiganj_sadar', label: 'Munshiganj Sadar', labelBn: 'মুন্সিগঞ্জ সদর', parentValue: 'munshiganj' },
  { value: 'sirajdikhan', label: 'Sirajdikhan', labelBn: 'সিরাজদিখান', parentValue: 'munshiganj' },
  { value: 'sreenagar', label: 'Sreenagar', labelBn: 'শ্রীনগর', parentValue: 'munshiganj' },
  { value: 'tongibari', label: 'Tongibari', labelBn: 'টংগীবাড়ি', parentValue: 'munshiganj' },
  { value: 'bhaluka', label: 'Bhaluka', labelBn: 'ভালুকা', parentValue: 'mymensingh' },
  { value: 'dhobaura', label: 'Dhobaura', labelBn: 'ধোবাউড়া', parentValue: 'mymensingh' },
  { value: 'fulbaria', label: 'Fulbaria', labelBn: 'ফুলবাড়ীয়া', parentValue: 'mymensingh' },
  { value: 'gafargaon', label: 'Gafargaon', labelBn: 'গফরগাঁও', parentValue: 'mymensingh' },
  { value: 'gouripur', label: 'Gouripur', labelBn: 'গৌরীপুর', parentValue: 'mymensingh' },
  { value: 'haluaghat', label: 'Haluaghat', labelBn: 'হালুয়াঘাট', parentValue: 'mymensingh' },
  { value: 'iswarganj', label: 'Iswarganj', labelBn: 'ঈশ্বরগঞ্জ', parentValue: 'mymensingh' },
  { value: 'muktagacha', label: 'Muktagacha', labelBn: 'মুক্তাগাছা', parentValue: 'mymensingh' },
  { value: 'mymensingh_sadar', label: 'Mymensingh Sadar', labelBn: 'ময়মনসিংহ সদর', parentValue: 'mymensingh' },
  { value: 'nandail', label: 'Nandail', labelBn: 'নান্দাইল', parentValue: 'mymensingh' },
  { value: 'phulpur', label: 'Phulpur', labelBn: 'ফুলপুর', parentValue: 'mymensingh' },
  { value: 'tarakanda', label: 'Tarakanda', labelBn: 'তারাকান্দা', parentValue: 'mymensingh' },
  { value: 'trishal', label: 'Trishal', labelBn: 'ত্রিশাল', parentValue: 'mymensingh' },
  { value: 'atrai', label: 'Atrai', labelBn: 'আত্রাই', parentValue: 'naogaon' },
  { value: 'badalgachi', label: 'Badalgachi', labelBn: 'বদলগাছী', parentValue: 'naogaon' },
  { value: 'dhamoirhat', label: 'Dhamoirhat', labelBn: 'ধামইরহাট', parentValue: 'naogaon' },
  { value: 'manda', label: 'Manda', labelBn: 'মান্দা', parentValue: 'naogaon' },
  { value: 'mohadevpur', label: 'Mohadevpur', labelBn: 'মহাদেবপুর', parentValue: 'naogaon' },
  { value: 'naogaon_sadar', label: 'Naogaon Sadar', labelBn: 'নওগাঁ সদর', parentValue: 'naogaon' },
  { value: 'niamatpur', label: 'Niamatpur', labelBn: 'নিয়ামতপুর', parentValue: 'naogaon' },
  { value: 'patnitala', label: 'Patnitala', labelBn: 'পত্নিতলা', parentValue: 'naogaon' },
  { value: 'porsha', label: 'Porsha', labelBn: 'পোরশা', parentValue: 'naogaon' },
  { value: 'raninagar', label: 'Raninagar', labelBn: 'রাণীনগর', parentValue: 'naogaon' },
  { value: 'sapahar', label: 'Sapahar', labelBn: 'সাপাহার', parentValue: 'naogaon' },
  { value: 'kalia', label: 'Kalia', labelBn: 'কালিয়া', parentValue: 'narail' },
  { value: 'lohagara', label: 'Lohagara', labelBn: 'লোহাগড়া', parentValue: 'narail' },
  { value: 'narail_sadar', label: 'Narail Sadar', labelBn: 'নড়াইল সদর', parentValue: 'narail' },
  { value: 'araihazar', label: 'Araihazar', labelBn: 'আড়াইহাজার', parentValue: 'narayanganj' },
  { value: 'bandar', label: 'Bandar', labelBn: 'বন্দর', parentValue: 'narayanganj' },
  { value: 'narayanganj_sadar', label: 'Narayanganj Sadar', labelBn: 'নারায়নগঞ্জ সদর', parentValue: 'narayanganj' },
  { value: 'rupganj', label: 'Rupganj', labelBn: 'রূপগঞ্জ', parentValue: 'narayanganj' },
  { value: 'sonargaon', label: 'Sonargaon', labelBn: 'সোনারগাঁ', parentValue: 'narayanganj' },
  { value: 'belabo', label: 'Belabo', labelBn: 'বেলাবো', parentValue: 'narsingdi' },
  { value: 'monohardi', label: 'Monohardi', labelBn: 'মনোহরদী', parentValue: 'narsingdi' },
  { value: 'narsingdi_sadar', label: 'Narsingdi Sadar', labelBn: 'নরসিংদী সদর', parentValue: 'narsingdi' },
  { value: 'palash', label: 'Palash', labelBn: 'পলাশ', parentValue: 'narsingdi' },
  { value: 'raipura', label: 'Raipura', labelBn: 'রায়পুরা', parentValue: 'narsingdi' },
  { value: 'shibpur', label: 'Shibpur', labelBn: 'শিবপুর', parentValue: 'narsingdi' },
  { value: 'bagatipara', label: 'Bagatipara', labelBn: 'বাগাতিপাড়া', parentValue: 'natore' },
  { value: 'baraigram', label: 'Baraigram', labelBn: 'বড়াইগ্রাম', parentValue: 'natore' },
  { value: 'gurudaspur', label: 'Gurudaspur', labelBn: 'গুরুদাসপুর', parentValue: 'natore' },
  { value: 'lalpur', label: 'Lalpur', labelBn: 'লালপুর', parentValue: 'natore' },
  { value: 'naldanga', label: 'Naldanga', labelBn: 'নলডাঙ্গা', parentValue: 'natore' },
  { value: 'natore_sadar', label: 'Natore Sadar', labelBn: 'নাটোর সদর', parentValue: 'natore' },
  { value: 'singra', label: 'Singra', labelBn: 'সিংড়া', parentValue: 'natore' },
  { value: 'atpara', label: 'Atpara', labelBn: 'আটপাড়া', parentValue: 'netrokona' },
  { value: 'barhatta', label: 'Barhatta', labelBn: 'বারহাট্টা', parentValue: 'netrokona' },
  { value: 'durgapur', label: 'Durgapur', labelBn: 'দুর্গাপুর', parentValue: 'netrokona' },
  { value: 'kalmakanda', label: 'Kalmakanda', labelBn: 'কলমাকান্দা', parentValue: 'netrokona' },
  { value: 'kendua', label: 'Kendua', labelBn: 'কেন্দুয়া', parentValue: 'netrokona' },
  { value: 'khaliajuri', label: 'Khaliajuri', labelBn: 'খালিয়াজুরী', parentValue: 'netrokona' },
  { value: 'madan', label: 'Madan', labelBn: 'মদন', parentValue: 'netrokona' },
  { value: 'mohongonj', label: 'Mohongonj', labelBn: 'মোহনগঞ্জ', parentValue: 'netrokona' },
  { value: 'netrokona_sadar', label: 'Netrokona Sadar', labelBn: 'নেত্রকোণা সদর', parentValue: 'netrokona' },
  { value: 'purbadhala', label: 'Purbadhala', labelBn: 'পূর্বধলা', parentValue: 'netrokona' },
  { value: 'dimla', label: 'Dimla', labelBn: 'ডিমলা', parentValue: 'nilphamari' },
  { value: 'domar', label: 'Domar', labelBn: 'ডোমার', parentValue: 'nilphamari' },
  { value: 'jaldhaka', label: 'Jaldhaka', labelBn: 'জলঢাকা', parentValue: 'nilphamari' },
  { value: 'kishorganj', label: 'Kishorganj', labelBn: 'কিশোরগঞ্জ', parentValue: 'nilphamari' },
  { value: 'nilphamari_sadar', label: 'Nilphamari Sadar', labelBn: 'নীলফামারী সদর', parentValue: 'nilphamari' },
  { value: 'syedpur', label: 'Syedpur', labelBn: 'সৈয়দপুর', parentValue: 'nilphamari' },
  { value: 'begumganj', label: 'Begumganj', labelBn: 'বেগমগঞ্জ', parentValue: 'noakhali' },
  { value: 'chatkhil', label: 'Chatkhil', labelBn: 'চাটখিল', parentValue: 'noakhali' },
  { value: 'companiganj', label: 'Companiganj', labelBn: 'কোম্পানীগঞ্জ', parentValue: 'noakhali' },
  { value: 'hatia', label: 'Hatia', labelBn: 'হাতিয়া', parentValue: 'noakhali' },
  { value: 'kabirhat', label: 'Kabirhat', labelBn: 'কবিরহাট', parentValue: 'noakhali' },
  { value: 'noakhali_sadar', label: 'Noakhali Sadar', labelBn: 'নোয়াখালী সদর', parentValue: 'noakhali' },
  { value: 'senbug', label: 'Senbug', labelBn: 'সেনবাগ', parentValue: 'noakhali' },
  { value: 'sonaimori', label: 'Sonaimori', labelBn: 'সোনাইমুড়ী', parentValue: 'noakhali' },
  { value: 'subarnachar', label: 'Subarnachar', labelBn: 'সুবর্ণচর', parentValue: 'noakhali' },
  { value: 'atghoria', label: 'Atghoria', labelBn: 'আটঘরিয়া', parentValue: 'pabna' },
  { value: 'bera', label: 'Bera', labelBn: 'বেড়া', parentValue: 'pabna' },
  { value: 'bhangura', label: 'Bhangura', labelBn: 'ভাঙ্গুড়া', parentValue: 'pabna' },
  { value: 'chatmohar', label: 'Chatmohar', labelBn: 'চাটমোহর', parentValue: 'pabna' },
  { value: 'faridpur', label: 'Faridpur', labelBn: 'ফরিদপুর', parentValue: 'pabna' },
  { value: 'ishurdi', label: 'Ishurdi', labelBn: 'ঈশ্বরদী', parentValue: 'pabna' },
  { value: 'pabna_sadar', label: 'Pabna Sadar', labelBn: 'পাবনা সদর', parentValue: 'pabna' },
  { value: 'santhia', label: 'Santhia', labelBn: 'সাঁথিয়া', parentValue: 'pabna' },
  { value: 'sujanagar', label: 'Sujanagar', labelBn: 'সুজানগর', parentValue: 'pabna' },
  { value: 'atwari', label: 'Atwari', labelBn: 'আটোয়ারী', parentValue: 'panchagarh' },
  { value: 'boda', label: 'Boda', labelBn: 'বোদা', parentValue: 'panchagarh' },
  { value: 'debiganj', label: 'Debiganj', labelBn: 'দেবীগঞ্জ', parentValue: 'panchagarh' },
  { value: 'panchagarh_sadar', label: 'Panchagarh Sadar', labelBn: 'পঞ্চগড় সদর', parentValue: 'panchagarh' },
  { value: 'tetulia', label: 'Tetulia', labelBn: 'তেতুলিয়া', parentValue: 'panchagarh' },
  { value: 'bauphal', label: 'Bauphal', labelBn: 'বাউফল', parentValue: 'patuakhali' },
  { value: 'dashmina', label: 'Dashmina', labelBn: 'দশমিনা', parentValue: 'patuakhali' },
  { value: 'dumki', label: 'Dumki', labelBn: 'দুমকি', parentValue: 'patuakhali' },
  { value: 'galachipa', label: 'Galachipa', labelBn: 'গলাচিপা', parentValue: 'patuakhali' },
  { value: 'kalapara', label: 'Kalapara', labelBn: 'কলাপাড়া', parentValue: 'patuakhali' },
  { value: 'mirzaganj', label: 'Mirzaganj', labelBn: 'মির্জাগঞ্জ', parentValue: 'patuakhali' },
  { value: 'patuakhali_sadar', label: 'Patuakhali Sadar', labelBn: 'পটুয়াখালী সদর', parentValue: 'patuakhali' },
  { value: 'rangabali', label: 'Rangabali', labelBn: 'রাঙ্গাবালী', parentValue: 'patuakhali' },
  { value: 'bhandaria', label: 'Bhandaria', labelBn: 'ভান্ডারিয়া', parentValue: 'pirojpur' },
  { value: 'indurkani', label: 'Indurkani', labelBn: 'ইন্দুরকানী', parentValue: 'pirojpur' },
  { value: 'kawkhali', label: 'Kawkhali', labelBn: 'কাউখালী', parentValue: 'pirojpur' },
  { value: 'mathbaria', label: 'Mathbaria', labelBn: 'মঠবাড়ীয়া', parentValue: 'pirojpur' },
  { value: 'nazirpur', label: 'Nazirpur', labelBn: 'নাজিরপুর', parentValue: 'pirojpur' },
  { value: 'nesarabad', label: 'Nesarabad', labelBn: 'নেছারাবাদ', parentValue: 'pirojpur' },
  { value: 'pirojpur_sadar', label: 'Pirojpur Sadar', labelBn: 'পিরোজপুর সদর', parentValue: 'pirojpur' },
  { value: 'baliakandi', label: 'Baliakandi', labelBn: 'বালিয়াকান্দি', parentValue: 'rajbari' },
  { value: 'goalanda', label: 'Goalanda', labelBn: 'গোয়ালন্দ', parentValue: 'rajbari' },
  { value: 'kalukhali', label: 'Kalukhali', labelBn: 'কালুখালী', parentValue: 'rajbari' },
  { value: 'pangsa', label: 'Pangsa', labelBn: 'পাংশা', parentValue: 'rajbari' },
  { value: 'rajbari_sadar', label: 'Rajbari Sadar', labelBn: 'রাজবাড়ী সদর', parentValue: 'rajbari' },
  { value: 'bagha', label: 'Bagha', labelBn: 'বাঘা', parentValue: 'rajshahi' },
  { value: 'bagmara', label: 'Bagmara', labelBn: 'বাগমারা', parentValue: 'rajshahi' },
  { value: 'charghat', label: 'Charghat', labelBn: 'চারঘাট', parentValue: 'rajshahi' },
  { value: 'durgapur', label: 'Durgapur', labelBn: 'দুর্গাপুর', parentValue: 'rajshahi' },
  { value: 'godagari', label: 'Godagari', labelBn: 'গোদাগাড়ী', parentValue: 'rajshahi' },
  { value: 'mohonpur', label: 'Mohonpur', labelBn: 'মোহনপুর', parentValue: 'rajshahi' },
  { value: 'paba', label: 'Paba', labelBn: 'পবা', parentValue: 'rajshahi' },
  { value: 'puthia', label: 'Puthia', labelBn: 'পুঠিয়া', parentValue: 'rajshahi' },
  { value: 'tanore', label: 'Tanore', labelBn: 'তানোর', parentValue: 'rajshahi' },
  { value: 'baghaichari', label: 'Baghaichari', labelBn: 'বাঘাইছড়ি', parentValue: 'rangamati' },
  { value: 'barkal', label: 'Barkal', labelBn: 'বরকল', parentValue: 'rangamati' },
  { value: 'belaichari', label: 'Belaichari', labelBn: 'বিলাইছড়ি', parentValue: 'rangamati' },
  { value: 'juraichari', label: 'Juraichari', labelBn: 'জুরাছড়ি', parentValue: 'rangamati' },
  { value: 'kaptai', label: 'Kaptai', labelBn: 'কাপ্তাই', parentValue: 'rangamati' },
  { value: 'kawkhali', label: 'Kawkhali', labelBn: 'কাউখালী', parentValue: 'rangamati' },
  { value: 'langadu', label: 'Langadu', labelBn: 'লংগদু', parentValue: 'rangamati' },
  { value: 'naniarchar', label: 'Naniarchar', labelBn: 'নানিয়ারচর', parentValue: 'rangamati' },
  { value: 'rajasthali', label: 'Rajasthali', labelBn: 'রাজস্থলী', parentValue: 'rangamati' },
  { value: 'rangamati_sadar', label: 'Rangamati Sadar', labelBn: 'রাঙ্গামাটি সদর', parentValue: 'rangamati' },
  { value: 'badargonj', label: 'Badargonj', labelBn: 'বদরগঞ্জ', parentValue: 'rangpur' },
  { value: 'gangachara', label: 'Gangachara', labelBn: 'গংগাচড়া', parentValue: 'rangpur' },
  { value: 'kaunia', label: 'Kaunia', labelBn: 'কাউনিয়া', parentValue: 'rangpur' },
  { value: 'mithapukur', label: 'Mithapukur', labelBn: 'মিঠাপুকুর', parentValue: 'rangpur' },
  { value: 'pirgacha', label: 'Pirgacha', labelBn: 'পীরগাছা', parentValue: 'rangpur' },
  { value: 'pirgonj', label: 'Pirgonj', labelBn: 'পীরগঞ্জ', parentValue: 'rangpur' },
  { value: 'rangpur_sadar', label: 'Rangpur Sadar', labelBn: 'রংপুর সদর', parentValue: 'rangpur' },
  { value: 'taragonj', label: 'Taragonj', labelBn: 'তারাগঞ্জ', parentValue: 'rangpur' },
  { value: 'assasuni', label: 'Assasuni', labelBn: 'আশাশুনি', parentValue: 'satkhira' },
  { value: 'debhata', label: 'Debhata', labelBn: 'দেবহাটা', parentValue: 'satkhira' },
  { value: 'kalaroa', label: 'Kalaroa', labelBn: 'কলারোয়া', parentValue: 'satkhira' },
  { value: 'kaliganj', label: 'Kaliganj', labelBn: 'কালিগঞ্জ', parentValue: 'satkhira' },
  { value: 'satkhira_sadar', label: 'Satkhira Sadar', labelBn: 'সাতক্ষীরা সদর', parentValue: 'satkhira' },
  { value: 'shyamnagar', label: 'Shyamnagar', labelBn: 'শ্যামনগর', parentValue: 'satkhira' },
  { value: 'tala', label: 'Tala', labelBn: 'তালা', parentValue: 'satkhira' },
  { value: 'bhedarganj', label: 'Bhedarganj', labelBn: 'ভেদরগঞ্জ', parentValue: 'shariatpur' },
  { value: 'damudya', label: 'Damudya', labelBn: 'ডামুড্যা', parentValue: 'shariatpur' },
  { value: 'gosairhat', label: 'Gosairhat', labelBn: 'গোসাইরহাট', parentValue: 'shariatpur' },
  { value: 'naria', label: 'Naria', labelBn: 'নড়িয়া', parentValue: 'shariatpur' },
  { value: 'shariatpur_sadar', label: 'Shariatpur Sadar', labelBn: 'শরিয়তপুর সদর', parentValue: 'shariatpur' },
  { value: 'zajira', label: 'Zajira', labelBn: 'জাজিরা', parentValue: 'shariatpur' },
  { value: 'jhenaigati', label: 'Jhenaigati', labelBn: 'ঝিনাইগাতী', parentValue: 'sherpur' },
  { value: 'nalitabari', label: 'Nalitabari', labelBn: 'নালিতাবাড়ী', parentValue: 'sherpur' },
  { value: 'nokla', label: 'Nokla', labelBn: 'নকলা', parentValue: 'sherpur' },
  { value: 'sherpur_sadar', label: 'Sherpur Sadar', labelBn: 'শেরপুর সদর', parentValue: 'sherpur' },
  { value: 'sreebordi', label: 'Sreebordi', labelBn: 'শ্রীবরদী', parentValue: 'sherpur' },
  { value: 'belkuchi', label: 'Belkuchi', labelBn: 'বেলকুচি', parentValue: 'sirajganj' },
  { value: 'chauhali', label: 'Chauhali', labelBn: 'চৌহালি', parentValue: 'sirajganj' },
  { value: 'kamarkhand', label: 'Kamarkhand', labelBn: 'কামারখন্দ', parentValue: 'sirajganj' },
  { value: 'kazipur', label: 'Kazipur', labelBn: 'কাজীপুর', parentValue: 'sirajganj' },
  { value: 'raigonj', label: 'Raigonj', labelBn: 'রায়গঞ্জ', parentValue: 'sirajganj' },
  { value: 'shahjadpur', label: 'Shahjadpur', labelBn: 'শাহজাদপুর', parentValue: 'sirajganj' },
  { value: 'sirajganj_sadar', label: 'Sirajganj Sadar', labelBn: 'সিরাজগঞ্জ সদর', parentValue: 'sirajganj' },
  { value: 'tarash', label: 'Tarash', labelBn: 'তাড়াশ', parentValue: 'sirajganj' },
  { value: 'ullapara', label: 'Ullapara', labelBn: 'উল্লাপাড়া', parentValue: 'sirajganj' },
  { value: 'bishwambarpur', label: 'Bishwambarpur', labelBn: 'বিশ্বম্ভরপুর', parentValue: 'sunamganj' },
  { value: 'chhatak', label: 'Chhatak', labelBn: 'ছাতক', parentValue: 'sunamganj' },
  { value: 'derai', label: 'Derai', labelBn: 'দিরাই', parentValue: 'sunamganj' },
  { value: 'dharmapasha', label: 'Dharmapasha', labelBn: 'ধর্মপাশা', parentValue: 'sunamganj' },
  { value: 'dowarabazar', label: 'Dowarabazar', labelBn: 'দোয়ারাবাজার', parentValue: 'sunamganj' },
  { value: 'jagannathpur', label: 'Jagannathpur', labelBn: 'জগন্নাথপুর', parentValue: 'sunamganj' },
  { value: 'jamalganj', label: 'Jamalganj', labelBn: 'জামালগঞ্জ', parentValue: 'sunamganj' },
  { value: 'madhyanagar', label: 'Madhyanagar', labelBn: 'মধ্যনগর', parentValue: 'sunamganj' },
  { value: 'shalla', label: 'Shalla', labelBn: 'শাল্লা', parentValue: 'sunamganj' },
  { value: 'shantiganj', label: 'Shantiganj', labelBn: 'শান্তিগঞ্জ', parentValue: 'sunamganj' },
  { value: 'sunamganj_sadar', label: 'Sunamganj Sadar', labelBn: 'সুনামগঞ্জ সদর', parentValue: 'sunamganj' },
  { value: 'tahirpur', label: 'Tahirpur', labelBn: 'তাহিরপুর', parentValue: 'sunamganj' },
  { value: 'balaganj', label: 'Balaganj', labelBn: 'বালাগঞ্জ', parentValue: 'sylhet' },
  { value: 'beanibazar', label: 'Beanibazar', labelBn: 'বিয়ানীবাজার', parentValue: 'sylhet' },
  { value: 'bishwanath', label: 'Bishwanath', labelBn: 'বিশ্বনাথ', parentValue: 'sylhet' },
  { value: 'companiganj', label: 'Companiganj', labelBn: 'কোম্পানীগঞ্জ', parentValue: 'sylhet' },
  { value: 'dakshinsurma', label: 'Dakshinsurma', labelBn: 'দক্ষিণ সুরমা', parentValue: 'sylhet' },
  { value: 'fenchuganj', label: 'Fenchuganj', labelBn: 'ফেঞ্চুগঞ্জ', parentValue: 'sylhet' },
  { value: 'golapganj', label: 'Golapganj', labelBn: 'গোলাপগঞ্জ', parentValue: 'sylhet' },
  { value: 'gowainghat', label: 'Gowainghat', labelBn: 'গোয়াইনঘাট', parentValue: 'sylhet' },
  { value: 'jaintiapur', label: 'Jaintiapur', labelBn: 'জৈন্তাপুর', parentValue: 'sylhet' },
  { value: 'kanaighat', label: 'Kanaighat', labelBn: 'কানাইঘাট', parentValue: 'sylhet' },
  { value: 'osmaninagar', label: 'Osmaninagar', labelBn: 'ওসমানী নগর', parentValue: 'sylhet' },
  { value: 'sylhet_sadar', label: 'Sylhet Sadar', labelBn: 'সিলেট সদর', parentValue: 'sylhet' },
  { value: 'zakiganj', label: 'Zakiganj', labelBn: 'জকিগঞ্জ', parentValue: 'sylhet' },
  { value: 'basail', label: 'Basail', labelBn: 'বাসাইল', parentValue: 'tangail' },
  { value: 'bhuapur', label: 'Bhuapur', labelBn: 'ভুয়াপুর', parentValue: 'tangail' },
  { value: 'delduar', label: 'Delduar', labelBn: 'দেলদুয়ার', parentValue: 'tangail' },
  { value: 'dhanbari', label: 'Dhanbari', labelBn: 'ধনবাড়ী', parentValue: 'tangail' },
  { value: 'ghatail', label: 'Ghatail', labelBn: 'ঘাটাইল', parentValue: 'tangail' },
  { value: 'gopalpur', label: 'Gopalpur', labelBn: 'গোপালপুর', parentValue: 'tangail' },
  { value: 'kalihati', label: 'Kalihati', labelBn: 'কালিহাতী', parentValue: 'tangail' },
  { value: 'madhupur', label: 'Madhupur', labelBn: 'মধুপুর', parentValue: 'tangail' },
  { value: 'mirzapur', label: 'Mirzapur', labelBn: 'মির্জাপুর', parentValue: 'tangail' },
  { value: 'nagarpur', label: 'Nagarpur', labelBn: 'নাগরপুর', parentValue: 'tangail' },
  { value: 'sakhipur', label: 'Sakhipur', labelBn: 'সখিপুর', parentValue: 'tangail' },
  { value: 'tangail_sadar', label: 'Tangail Sadar', labelBn: 'টাঙ্গাইল সদর', parentValue: 'tangail' },
  { value: 'baliadangi', label: 'Baliadangi', labelBn: 'বালিয়াডাঙ্গী', parentValue: 'thakurgaon' },
  { value: 'haripur', label: 'Haripur', labelBn: 'হরিপুর', parentValue: 'thakurgaon' },
  { value: 'pirganj', label: 'Pirganj', labelBn: 'পীরগঞ্জ', parentValue: 'thakurgaon' },
  { value: 'ranisankail', label: 'Ranisankail', labelBn: 'রাণীশংকৈল', parentValue: 'thakurgaon' },
  { value: 'thakurgaon_sadar', label: 'Thakurgaon Sadar', labelBn: 'ঠাকুরগাঁও সদর', parentValue: 'thakurgaon' },
];
