import type { ProfilePhoto } from "./media";

export type MemberProfile = {
  id: string;
  profileCode: string;
  creationMode?: "self" | "on_behalf" | null;
  onBehalfRelation?: string | null;
  fullName: string | null;
  gender: string | null;
  dateOfBirth: string | null;
  maritalStatus: string | null;
  divorceDetails: string | null;
  childrenCount: number | null;
  heightUnit: "cm" | "ft_in";
  heightCm: number | null;
  weightKg: number | null;
  complexion: string | null;
  hasDisability: boolean;
  disabilityInfo: string | null;
  religion: string | null;
  hasBeard: string | null;
  smokingHabit: string | null;
  expectedMarriageTimeline: string | null;
  dowryExpectation: string | null;
  weddingCeremonyPreference: string | null;
  expectedParenthoodTimeline: string | null;
  livingArrangements: string | null;
  livingArrangementsOther: string | null;
  expectedKabinAmountMinBdt: number | null;
  expectedKabinAmountMaxBdt: number | null;
  prayerPractice: string | null;
  hijabPractice: string | null;
  highestDegree: string | null;
  educationMedium: string | null;
  additionalEducationQualifications: string | null;
  institution: string | null;
  educationYear: number | null;
  educationSubject: string | null;
  occupation: string | null;
  company: string | null;
  designation: string | null;
  monthlyIncomeRange: string | null;
  currentCountry: string;
  currentDivision: string | null;
  currentDistrict: string | null;
  currentUpazila: string | null;
  currentCityTown: string | null;
  currentAddressLine: string | null;
  permanentCountry: string | null;
  permanentDivision: string | null;
  permanentDistrict: string | null;
  permanentUpazila: string | null;
  permanentCityTown: string | null;
  permanentAddressLine: string | null;
  permanentSameAsCurrent: boolean;
  biography: string | null;
  hobbies: string[];
  interests: string | null;
  introduction: string | null;
  isVerified: boolean;
  nidVerifiedAt: string | null;
  profileBiodataReviewStatus?: "pending" | "approved" | "rejected" | null;
  completionPercent: number;
  completionMissing: string[];
  photos?: ProfilePhoto[];
  familyInfo?: FamilyInfo | null;
  siblings?: SiblingFormEntry[];
  paternalRelatives?: RelativeFormEntry[];
  maternalRelatives?: RelativeFormEntry[];
  partnerPreference?: PartnerPreference | null;
};

export type FamilyInfo = {
  fatherName?: string | null;
  fatherIsAlive?: string | null;
  fatherEducation?: string | null;
  fatherProfession?: string | null;
  motherName?: string | null;
  motherIsAlive?: string | null;
  motherEducation?: string | null;
  motherProfession?: string | null;
  familyType?: string | null;
  familyStatus?: string | null;
  familyValues?: string | null;
  familyAssets?: string | null;
};

export type PartnerPreference = {
  ageMin?: number | null;
  ageMax?: number | null;
  heightMinCm?: number | null;
  heightMaxCm?: number | null;
  weightMinKg?: number | null;
  weightMaxKg?: number | null;
  preferredDistricts?: string[];
  preferredProfession?: string[];
  minimumEducation?: string | null;
  maritalStatusPref?: string[];
  additionalNotes?: string | null;
  beardPreference?: string | null;
  prayerPreference?: string | null;
  hijabPreference?: string | null;
};

export type SiblingFormEntry = {
  relationship: string;
  name: string;
  education: string;
  profession: string;
  maritalStatus: string;
  spouseName: string;
  spouseEducation: string;
  spouseProfession: string;
};

export type RelativeFormEntry = {
  relation: string;
  name: string;
  education: string;
  profession: string;
};

export type FamilyFormState = {
  fatherName: string;
  fatherIsAlive: string;
  fatherEducation: string;
  fatherProfession: string;
  motherName: string;
  motherIsAlive: string;
  motherEducation: string;
  motherProfession: string;
  familyType: string;
  familyStatus: string;
  familyValues: string;
  familyAssets: string;
  siblings: SiblingFormEntry[];
  paternalRelatives: RelativeFormEntry[];
  maternalRelatives: RelativeFormEntry[];
};

export type PartnerFormState = {
  ageMin: string;
  ageMax: string;
  heightMinFeet: string;
  heightMinInches: string;
  heightMaxFeet: string;
  heightMaxInches: string;
  weightMinKg: string;
  weightMaxKg: string;
  preferredDistricts: string[];
  preferredProfession: string[];
  minimumEducation: string;
  beardPreference: string;
  prayerPreference: string;
  hijabPreference: string;
  maritalStatusPref: string[];
  additionalNotes: string;
};

export type MaritalFormState = {
  expectedMarriageTimeline: string;
  dowryExpectation: string;
  weddingCeremonyPreference: string;
  expectedParenthoodTimeline: string;
  livingArrangements: string;
  livingArrangementsOther: string;
  expectedKabinAmountMinBdt: string;
  expectedKabinAmountMaxBdt: string;
};

export type PersonalFormState = {
  fullName: string;
  gender: string;
  dateOfBirth: string;
  maritalStatus: string;
  divorceDetails: string;
  childrenCount: string;
  heightFeet: string;
  heightInches: string;
  weightKg: string;
  complexion: string;
  hasDisability: boolean;
  disabilityInfo: string;
  religion: string;
  hasBeard: string;
  smokingHabit: string;
  prayerPractice: string;
  hijabPractice: string;
  highestDegree: string;
  educationMedium: string;
  additionalEducationQualifications: string;
  institution: string;
  educationYear: string;
  educationSubject: string;
  occupation: string;
  company: string;
  designation: string;
  monthlyIncomeRange: string;
  currentCountry: string;
  currentDivision: string;
  currentDistrict: string;
  currentUpazila: string;
  currentCityTown: string;
  currentAddressLine: string;
  permanentCountry: string;
  permanentDivision: string;
  permanentDistrict: string;
  permanentUpazila: string;
  permanentCityTown: string;
  permanentAddressLine: string;
  permanentSameAsCurrent: boolean;
  biography: string;
  hobbies: string;
  interests: string;
  introduction: string;
};

export type ProfileEditorBootstrap = {
  termsAccepted: boolean;
  termsVersion?: string | null;
  currentTermsVersion?: string | null;
  termsDeclinedAt?: string | null;
  creationMode?: "self" | "on_behalf" | null;
  onBehalfRelation?: string | null;
  profile: MemberProfile | null;
  profileBiodataReviewStatus?: "pending" | "approved" | "rejected" | null;
  completionPercent: number;
  completionMissing: string[];
};
