export const DropdownCategory = {
  GENDER: 'gender',
  MARITAL_STATUS: 'marital_status',
  RELIGION: 'religion',
  COMPLEXION: 'complexion',
  EDUCATION: 'education',
  EDUCATION_MEDIUM: 'education_medium',
  EDUCATION_SUBJECT: 'education_subject',
  OCCUPATION: 'occupation',
  INCOME_RANGE: 'income_range',
  DIVISION: 'division',
  DISTRICT: 'district',
  UPAZILA: 'upazila',
  FAMILY_TYPE: 'family_type',
  FAMILY_STATUS: 'family_status',
  SIBLING_RELATIONSHIP: 'sibling_relationship',
  HAS_BEARD: 'has_beard',
  PRAYER_PRACTICE: 'prayer_practice',
  IS_ALIVE: 'is_alive',
  BEARD_PREFERENCE: 'beard_preference',
  PRAYER_PREFERENCE: 'prayer_preference',
  HIJAB_PRACTICE: 'hijab_practice',
  HIJAB_PREFERENCE: 'hijab_preference',
  SMOKING_HABIT: 'smoking_habit',
  EXPECTED_MARRIAGE_TIMELINE: 'expected_marriage_timeline',
  DOWRY_EXPECTATION: 'dowry_expectation',
  WEDDING_CEREMONY_PREFERENCE: 'wedding_ceremony_preference',
  EXPECTED_PARENTHOOD_TIMELINE: 'expected_parenthood_timeline',
  LIVING_ARRANGEMENTS_MALE: 'living_arrangements_male',
  LIVING_ARRANGEMENTS_FEMALE: 'living_arrangements_female',
} as const;

export type DropdownCategory =
  (typeof DropdownCategory)[keyof typeof DropdownCategory];
